### ISSUE TITLE
naming conflict with Debian package maildir-utils (mu upstream)

### ISSUE THREAD

**Issue by pabs3** [skx/maildir-tools#2]
I noticed that Debian has a [maildir-utils package](https://packages.debian.org/sid/maildir-utils) already, which packages the [mu](https://www.djcbsoftware.nl/code/mu/) upstream project.

In any case, "maildir-utils" is a fairly generic name for software that operates on Maildirs :)

**Comment by skx** [comment]
Thanks for the report!  The collision is unfortunate, and picking names is hard.

I'm still 50/50 on whether this will be more useful as a scripting-tool, or as a console-based client.   I suspect the former, rather than the latter so I guess `maildir-tool` is a reasonable choice for a new-name.

I'm tied up tonight, but tomorrow I expect to dedicate some time to cleaning up and reorganizing the implementation into more idiomatic code.  When I do that I'll handle the renaming process too.

**Comment by skx** [comment]
Flurry of activity has resulted in a renamed repository, and CLI.  Documentation, packages, etc, all updated to match:

* https://github.com/skx/maildir-tools/
